language: node_js
node_js:
 - "5.10"
script:
 - tsc
 - npm run test-travis
# Send coverage data to Coveralls
after_script:
 - remap-istanbul -i ./coverage/coverage.json -t lcovonly > ./coverage/lcov-remap.info
 - cat ./coverage/lcov-remap.info | ./node_modules/coveralls/bin/coveralls.js